### ISSUE TITLE
Hive connectivity error - AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'

### ISSUE THREAD

**Issue by madhavvishnubhatta** [baztian/jaydebeapi#131]
I am trying to connect from Python to a hive DB. But I get the following error.

AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'

I am not fully sure if this is a bug, but I tried using the JDBC Uber Driver too and it didnt work.

I am using Open JDK 13, 
JayDeBeAPI version is 1.1.1
JPype1 version 0.7.2
Python version is 3.7.6
Hive JDBC Driver version is 3.1.2. downloaded from https://repo1.maven.org/maven2/org/apache/hive/hive-jdbc/3.1.2/hive-jdbc-3.1.2.jar
OS is Amazon Linux on an EC2

Any help in letting me know if this is a bug, or if I am doing something wrong will be appreciated.

Here is the full code:

```bash
$ python
Python 3.7.6 (default, Feb 26 2020, 20:54:15)
[GCC 7.3.1 20180712 (Red Hat 7.3.1-6)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.getenv("JAVA_HOME")
'/opt/jdk-13'
>>> import jaydebeapi
>>> conn=jaydebeapi.connect("org.apache.hive.jdbc.HiveDriver", "jdbc:hive2://0.0.0.0:10000", [], "/home/airflow/hive-jdbc-3.1.2.jar")
/home/airflow/airflow-env/lib64/python3.7/site-packages/jpype/_core.py:217: UserWarning:
-------------------------------------------------------------------------------
Deprecated: convertStrings was not specified when starting the JVM. The default
behavior in JPype will be False starting in JPype 0.8. The recommended setting
for new code is convertStrings=False.  The legacy value of True was assumed for
this session. If you are a user of an application that reported this warning,
please file a ticket with the developer.
-------------------------------------------------------------------------------

  """)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/airflow/airflow-env/lib64/python3.7/site-packages/jaydebeapi/__init__.py", line 381, in connect
    jconn = _jdbc_connect(jclassname, url, driver_args, jars, libs)
  File "/home/airflow/airflow-env/lib64/python3.7/site-packages/jaydebeapi/__init__.py", line 182, in _jdbc_connect_jpype
    for i in types.__javaclass__.getClassFields():
AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'
```

**Comment by madhavvishnubhatta** [comment]
This seems to be an issue with jpype1 module. When I downgraded JPype1 to 0.6.3 (with the command ```pip install --upgrade jpype1==0.6.3```), the issue disappeared. I am not sure if it is an issue with how JayDeBeApi invokes JPype1 or if it is a true JPype1 issue. If someone can confirm that the issue is indeed with JPype1, then I can close this issue.

**Comment by FahaoTang** [comment]
I got same error when connecting to SQLite or SQL Server after upgrading jpype1 to the latest version. After I downgraded as @madhavvishnubhatta  mentioned, it also worked for my case:
[AttributeError: type object 'java.sql.Types' has no attribute '__javaclass__'](https://kontext.tech/column/python/407/attributeerror-type-object-javasqltypes-has-no-attribute_javaclass)

**Comment by reinderien** [comment]
When using jaydebeapi, Ucanaccess, and jpype1 with any version after 0.6.3, I see this same problem.

**Comment by th0ger** [comment]
Same story, jaydebeapi 1.1.1, UCanAccess, jpype 0.7.4. failed, downgrading to jpype 0.6.3 worked.

I developed the code about a month ago, where it worked. It did not explicitely install jpype 0.6.3 IIRC, I did only specify the latest jaydebeapi in my requirements file. Now when reinstalling the project in a new venv, jaydebeapi causes the latest jpype 0.7.4 to be installed.
A bit puzzled about how i got the 2-year old jpype 0.6.3 was installed in the first place.

https://pypi.org/project/JPype1/#history

**Comment by th0ger** [comment]
Proposing to remove "Hive" from the topic, as this is a general issue.

**Comment by baztian** [comment]
Hi all together, is this still an issue with the most recent JayDeBeApi 1.2.1?

**Comment by reinderien** [comment]
It seems the issue has been fixed, at least on my platform:

- Windows
- Python 3.8.3
- jpype1 0.7.5
- JayDeBeApi 1.2.1

**Comment by gamblenull1996** [comment]
This problem has been fixed , just upgrade to JayDeBeApi to 1.2.3, JPype1 to 0.7.5

**Comment by baztian** [comment]
Thanks for the feedback @reinderien  and @gamblenull1996 ! I'm closing this one.

**Comment by ValerioVannicola** [comment]
I still have the same problem with the latest version of JayDeBEApi (1.2.3) and JPype1 (0.7.5). Could anybody help me? thanks

**Comment by theglob** [comment]
> This problem has been fixed , just upgrade to JayDeBeApi to 1.2.3, JPype1 to 0.7.5

i uninstalled  JPype1 and just installed the newest version of JayDeBeApi and it worked again.
