### ISSUE TITLE
Issues connecting to Redshift

### ISSUE THREAD

**Issue by leoruhesh** [baztian/jaydebeapi#69]
Unable to connect to RedshiftDB using the Redshift JDBC driver ( versions 4.2/4.1/4.0 ). 

When trying to connect to Redshift DB using 
jaydebeapi.connect(jclassname='com.amazon.redshift.jdbc.Driver', url=str('jdbc:redshift://endpoint:port/database?UID=user&PWD=password'),jars='/path-to-RedshiftJDBC4-1.2.12.1017.jar') the below error is thrown.  

return jpype.java.sql.DriverManager.getConnection(url, *dargs)
jpype._jexception.NoClassDefFoundErrorPyRaisable: java.lang.NoClassDefFoundError: Lcom/amazon/redshift/core/jdbc42/S42NotifiedConnection;

Tried 4.2/4.1/4.0 version of Redshift Drivers. Successfully able to connect using tools like Sql WorkBench.

**Comment by bgood** [comment]
I'm having the same issue.

Any updates on this?

**Comment by Mikuana** [comment]
Same. I'm trying to connect via SSO and getting this error.

**Comment by kathir2903** [comment]
Hi @Mikuana, @leoruhesh @bgood , Issue is fixed in 1.2.15
Here is the link to download - https://s3.amazonaws.com/redshift-downloads/drivers/jdbc/1.2.15.1025/RedshiftJDBC42-no-awssdk-1.2.15.1025.jar

Documentation - https://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html

**Comment by Mikuana** [comment]
@kathir2903 I may not understand the solution that you're suggesting, but I downloaded the new driver and I still get the same error. Both the no sdk and full sdk versions fail to authenticate via SSO. Did you update anything else to resolve this?

**Comment by kathir2903** [comment]
@Mikuana , The issue you have seen first was different than SSO. That issue is fixed in RedshiftJDBC42-no-awssdk-1.2.15.1025.jar, because I have tried the 1.2.15.1025 and it is working for me. SSO auth issue is different
